#!/usr/bin/bash

if ! command -v lsd > /dev/null
then
    curl -sLO https://github.com/Peltoche/lsd/releases/download/0.18.0/lsd_0.18.0_amd64.deb
    sudo apt install -y ./lsd_0.18.0_amd64.deb
    sudo rm lsd_0.18.0_amd64.deb
fi