#!/usr/bin/bash

if ! command -v op > /dev/null
then
    curl -sLO https://cache.agilebits.com/dist/1P/op/pkg/v1.8.0/op_linux_amd64_v1.8.0.zip
    unzip -q op_linux_amd64_v1.8.0.zip -d $HOME
    rm op_linux_amd64_v1.8.0.zip
    rm $HOME/op.sig
    sudo mv $HOME/op /usr/bin
else
    echo "One Password Already Installed."
fi