#!/usr/bin/bash

if ! command -v zsh > /dev/null
then
    sudo apt install zsh -y
fi

if [ "$SHELL" != "$(which zsh)" ]
then
    chsh -s $(which zsh) && echo "Default Shell set. Run su - [username] to make your updates."
else
    echo "already set"
fi